from __future__ import annotations

from api.pipeline.canonical_grammar.models import GrammarRule, GrammarAudience

CATALOG: list[GrammarRule] = [
    # --- 7.1 Encoding / Mojibake ---
    GrammarRule(
        id="GC-01-ENCODING-001",
        block="7.1 Encoding — Mojibake",
        title="Texto contiene caracteres mojibake que indican encoding roto",
        severity="critical",
        pattern="[\\u00C3\\u00C2\\u00E2\\uFFFD]",
        suggestion="Revise encoding UTF-8, tildes, ñ y signos de apertura.",
        rationale="El texto contiene caracteres incompatibles con una entrega canónica ARHIAX.",
    ),
    # --- 7.2 Terminología invariante ---
    GrammarRule(
        id="GC-02-TERM-001",
        block="7.2 Terminología invariante",
        title='ARHIAX debe escribirse en mayúsculas sostenidas',
        severity="major",
        pattern="\\b(?!(?:ARHIAX|arhiax_dx|arhiax_dxpro))[Aa]rhiax\\b",
        suggestion="ARHIAX",
        rationale="ARHIAX es sigla del corpus y se escribe siempre en versales.",
        audience=["client", "executive"],
    ),
    GrammarRule(
        id="GC-02-TERM-002",
        block="7.2 Terminología invariante",
        title='ARHIAX Dx Pro debe escribirse con espacio',
        severity="major",
        pattern="\\bARHIAX\\s+DxPro\\b",
        suggestion="ARHIAX Dx Pro",
        rationale="El nombre del producto separa Dx y Pro con un espacio.",
        audience=["client", "executive"],
    ),
    GrammarRule(
        id="GC-02-TERM-003",
        block="7.2 Terminología invariante",
        title="DxPro debe escribirse como Dx Pro (con espacio)",
        severity="major",
        pattern="(?<![a-zA-Z])(?<!dxpro_)DxPro(?!_)(?![a-zA-Z])",
        suggestion="Dx Pro",
        rationale="El nombre del producto separa Dx y Pro.",
        audience=["client", "executive"],
    ),
    GrammarRule(
        id="GC-02-TERM-004",
        block="7.2 Terminología invariante",
        title="DXPRO debe escribirse como Dx Pro en texto visible",
        severity="major",
        pattern="(?<![a-zA-Z])DXPRO(?![a-zA-Z])",
        suggestion="Dx Pro",
        rationale="DXPRO solo se usa en identificadores de sistema, no en texto visible.",
        audience=["client", "executive"],
    ),
    GrammarRule(
        id="GC-02-TERM-005",
        block="7.2 Terminología invariante",
        title='Governex debe escribirse con G mayúscula y sin "Thinking"',
        severity="major",
        pattern="\\bgovernex\\b",
        suggestion="Governex",
        rationale="Governex es nombre propio de la metodología de Sinergia Consulting Group.",
        audience=["client", "executive"],
    ),
    # --- 7.3 Coma de Oxford ---
    GrammarRule(
        id="GC-03-OXFORD-001",
        block="7.3 Coma de Oxford",
        title="Coma serial (Oxford) antes de la conjunción en enumeración",
        severity="minor",
        pattern=",\\s+(?:y|e|o|u)\\s+",
        suggestion="Elimine la coma antes de la conjunción.",
        rationale="La RAE desaconseja la coma antes de y/e/o/u en enumeraciones.",
        audience=["client"],
    ),
    # --- 7.4 Calcos del inglés ---
    GrammarRule(
        id="GC-04-CALCO-001",
        block="7.4 Calcos del inglés",
        title='"hacer sentido" es calco del inglés "make sense"',
        severity="major",
        pattern="(?:hace|hacen|hacer)\\s+sentido",
        suggestion="Use 'tiene sentido', 'es lógico', 'es razonable'.",
        rationale='"Hacer sentido" es calco directo del inglés "make sense".',
        audience=["client"],
    ),
    GrammarRule(
        id="GC-04-CALCO-002",
        block="7.4 Calcos del inglés",
        title='"en base a" es calco del inglés "based on"',
        severity="major",
        pattern="\\ben\\s+base\\s+a\\b",
        suggestion="Use 'con base en', 'a partir de', 'según'.",
        rationale='"En base a" es calco del inglés "based on". La RAE prefiere "con base en".',
        audience=["client"],
    ),
    GrammarRule(
        id="GC-04-CALCO-003",
        block="7.4 Calcos del inglés",
        title='"a nivel de" es calco del inglés "at the level of"',
        severity="major",
        pattern="\\ba\\s+nivel\\s+de\\b",
        suggestion="Use 'en cuanto a', 'respecto a', 'en el ámbito de'.",
        rationale='"A nivel de" es calco del inglés "at the level of".',
        audience=["client"],
    ),
    GrammarRule(
        id="GC-04-CALCO-004",
        block="7.4 Calcos del inglés",
        title='Estructura "sustantivo + a + infinitivo" es calco del inglés',
        severity="major",
        pattern="\\b(?:proyectos|procesos|actividades|tareas|iniciativas|propuestas|estrategias|metodologías|herramientas|soluciones|productos|servicios|programas|sistemas|modelos|planes|políticas|normas|reglas|acciones|funciones|responsabilidades|competencias|capacidades|habilidades|conocimientos|recursos|equipos|áreas|departamentos|unidades|divisiones|sedes|oficinas|sucursales|filiales|subsidiarias|empresas|organizaciones|instituciones|entidades|organismos|dependencias)\\s+a\\s+[a-z]",
        suggestion="Use preposición correcta según el contexto (para, de, por, etc.).",
        rationale='Estructura "sustantivo + a + infinitivo" es calco del inglés.',
        audience=["client"],
    ),
    GrammarRule(
        id="GC-04-CALCO-005",
        block="7.4 Calcos del inglés",
        title='"suena bien" es calco del inglés "sounds good"',
        severity="major",
        pattern="\\bsuena\\s+bien\\b",
        suggestion="Use 'es adecuado', 'es pertinente', 'es correcto'.",
        rationale='"Suena bien" es calco del inglés "sounds good".',
        audience=["client"],
    ),
    GrammarRule(
        id="GC-04-CALCO-006",
        block="7.4 Calcos del inglés",
        title='"se ve bien" es calco del inglés "looks good"',
        severity="major",
        pattern="\\bse\\s+ve\\s+bien\\b",
        suggestion="Use 'es correcto', 'es adecuado', 'está bien'.",
        rationale='"Se ve bien" es calco del inglés "looks good".',
        audience=["client"],
    ),
    # --- 7.5 Falsa fluidez ---
    GrammarRule(
        id="GC-05-FLUID-001",
        block="7.5 Falsa fluidez",
        title='Muletilla "Es importante mencionar que"',
        severity="advisory",
        pattern="\\bEs\\s+importante\\s+mencionar\\s+que\\b",
        suggestion="Elimine la muletilla. El contenido debe sostenerse por sí mismo.",
        rationale="Falsa fluidez que añade palabras sin contenido.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-05-FLUID-002",
        block="7.5 Falsa fluidez",
        title='Muletilla "Cabe destacar que"',
        severity="advisory",
        pattern="\\bCabe\\s+destacar\\s+que\\b",
        suggestion="Elimine la muletilla. El contenido debe sostenerse por sí mismo.",
        rationale="Falsa fluidez que añade palabras sin contenido.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-05-FLUID-003",
        block="7.5 Falsa fluidez",
        title='Muletilla "Vale la pena señalar que"',
        severity="advisory",
        pattern="\\bVale\\s+la\\s+pena\\s+señalar\\s+que\\b",
        suggestion="Elimine la muletilla. El contenido debe sostenerse por sí mismo.",
        rationale="Falsa fluidez que añade palabras sin contenido.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-05-FLUID-004",
        block="7.5 Falsa fluidez",
        title='Muletilla "Es relevante mencionar que"',
        severity="advisory",
        pattern="\\bEs\\s+relevante\\s+mencionar\\s+que\\b",
        suggestion="Elimine la muletilla. El contenido debe sostenerse por sí mismo.",
        rationale="Falsa fluidez que añade palabras sin contenido.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-05-FLUID-005",
        block="7.5 Falsa fluidez",
        title='Muletilla "No hay que olvidar que"',
        severity="advisory",
        pattern="\\bNo\\s+hay\\s+que\\s+olvidar\\s+que\\b",
        suggestion="Elimine la muletilla. El contenido debe sostenerse por sí mismo.",
        rationale="Falsa fluidez que añade palabras sin contenido.",
        audience=["client"],
    ),
    # --- 7.6 Ortografía RAE ---
    GrammarRule(
        id="GC-06-RAE-001",
        block="7.6 Ortografía — RAE",
        title="Mes con mayúscula inicial",
        severity="minor",
        pattern="\\b(?:Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre)\\b",
        suggestion="Los meses se escriben con minúscula inicial en español.",
        rationale="La RAE establece minúscula inicial para meses y días de la semana.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-06-RAE-002",
        block="7.6 Ortografía — RAE",
        title="Día de la semana con mayúscula inicial",
        severity="minor",
        pattern="\\b(?:Lunes|Martes|Miércoles|Jueves|Viernes|Sábado|Domingo)\\b",
        suggestion="Los días de la semana se escriben con minúscula inicial en español.",
        rationale="La RAE establece minúscula inicial para meses y días de la semana.",
        audience=["client"],
    ),
    # --- 7.7 Registro formal (términos internos en texto a cliente) ---
    GrammarRule(
        id="GC-07-REG-001",
        block="7.7 Registro formal",
        title='Término interno "custodio" en texto a cliente',
        severity="minor",
        pattern="\\bcustodio\\b",
        suggestion="Use un término más claro para el cliente.",
        rationale="'Custodio' es jerga interna del equipo de consultoría.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-07-REG-002",
        block="7.7 Registro formal",
        title='Término interno "desvelamiento" en texto a cliente',
        severity="minor",
        pattern="\\bdesvelamiento\\b",
        suggestion="Use 'revelación', 'divulgación' o 'apertura'.",
        rationale="'Desvelamiento' es jerga técnica interna.",
        audience=["client"],
    ),
    GrammarRule(
        id="GC-07-REG-003",
        block="7.7 Registro formal",
        title='Término interno "umbral" en texto a cliente',
        severity="minor",
        pattern="\\b(?:Umbral|umbrales)\\b",
        suggestion="Use 'límite', 'punto de referencia', 'nivel mínimo'.",
        rationale="'Umbral' es jerga técnica de scoring interno.",
        audience=["client"],
    ),
]

CATALOG_BY_ID: dict[str, GrammarRule] = {r.id: r for r in CATALOG}


def get_rules_for_audience(audience: GrammarAudience) -> list[GrammarRule]:
    result: list[GrammarRule] = []
    for rule in CATALOG:
        if rule.audience is None or audience in rule.audience:
            result.append(rule)
    return result
