/**
 * Pipeline presets by diagnostic depth.
 * The consultant picks Basic / Standard / Complete.
 * The system activates the right tools automatically.
 */

export const DEPTH_PRESETS = {
  basic: {
    label: "Básico",
    subtitle: "Mapeo rápido de procesos y hallazgos principales",
    duration: "3–5 días",
    tools: [
      "g01_receptor",
      "g02_configurador",
      "g04_cartografo",
      "g05_brechas",
      "g12_hallazgos",
      "g13_redactor",
    ],
    includes: [
      "Recepción y configuración del mandato",
      "Mapa de procesos organizacionales",
      "Identificación de brechas",
      "Hallazgos y recomendaciones",
      "Narrativa ejecutiva",
    ],
    excludes: [
      "Encuesta multi-rater",
      "Análisis Bayesiano",
      "Diagramas BPMN",
      "Reporte Word",
    ],
    color: "blue",
  },
  standard: {
    label: "Estándar",
    subtitle: "Diagnóstico completo con encuesta, scoring y análisis",
    duration: "7–10 días",
    tools: [
      "g01_receptor",
      "g02_configurador",
      "g03_cienciometro",
      "g04_cartografo",
      "g05_brechas",
      "g06_bpmn_architect",
      "g07_cuellos",
      "g09a_preguntas",
      "g09b_ramificacion",
      "g09c_validacion",
      "g10a_scoring",
      "g10b_psicometria",
      "g11a_bayesiano",
      "irr_calculator",
      "g12_hallazgos",
      "g13_redactor",
      "g14_qa_control",
    ],
    includes: [
      "Todo lo del plan Básico",
      "Revisión de literatura académica",
      "Arquitectura BPMN del proceso actual",
      "Cuantificación de cuellos de botella",
      "Encuesta multi-rater con scoring",
      "Análisis psicométrico y Bayesiano",
      "Control de calidad (QA)",
    ],
    excludes: [
      "Opciones TO-BE y ROI",
      "Reporte Word descargable",
    ],
    color: "brand",
  },
  complete: {
    label: "Completo",
    subtitle: "Pipeline total con diseño TO-BE, ROI y reporte Word",
    duration: "12–15 días",
    tools: [
      "g01_receptor",
      "g02_configurador",
      "g03_cienciometro",
      "academic_search",
      "web_search",
      "g04_cartografo",
      "g05_brechas",
      "g06_bpmn_architect",
      "g07_cuellos",
      "g08_optimizador",
      "bpmn_generator",
      "g09a_preguntas",
      "g09b_ramificacion",
      "g09c_validacion",
      "g10a_scoring",
      "g10b_psicometria",
      "g11a_bayesiano",
      "g11b_nlp",
      "irr_calculator",
      "scoring_engine",
      "g12_hallazgos",
      "g13_redactor",
      "g14_qa_control",
      "docx_generator",
    ],
    includes: [
      "Todo lo del plan Estándar",
      "Búsqueda académica y web sectorial",
      "Diseño de mejoras TO-BE y escenarios ROI",
      "Diagramas BPMN generados",
      "Análisis NLP de texto libre",
      "Reporte Word descargable y firmado",
    ],
    excludes: [],
    color: "navy",
  },
} as const;

export type DepthKey = keyof typeof DEPTH_PRESETS;

export const SECTORS = [
  "Manufactura",
  "Logística y transporte",
  "Servicios financieros",
  "Salud",
  "Retail y comercio",
  "Tecnología",
  "Construcción",
  "Educación",
  "Agroindustria",
  "Energía y utilities",
  "Gobierno y sector público",
  "Consultoría y servicios profesionales",
  "Otro",
];

export const AREAS = [
  "Operaciones y producción",
  "Recursos Humanos",
  "Ventas y comercial",
  "Logística y cadena de suministro",
  "Tecnología e innovación",
  "Finanzas y contabilidad",
  "Servicio al cliente",
  "Compras y abastecimiento",
  "Calidad",
  "Dirección y estrategia",
  "Otro",
];
