"""Survey models - Multi-rater survey system."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, _now, _uuid


class SurveySession(Base):
    """
    Multi-rater survey session generated by G09a agent.
    Pauses the diagnostic pipeline until minimum responses are collected.
    """
    __tablename__ = "survey_sessions"

    id: Mapped[str]            = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    diagnostic_id: Mapped[str] = mapped_column(ForeignKey("diagnostics.id"), unique=True, nullable=False)
    
    # Survey configuration
    token: Mapped[str]         = mapped_column(String, unique=True, nullable=False)  # URL token
    questions: Mapped[dict]    = mapped_column(JSONB, nullable=False)  # output de G09a
    branching: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # output de G09b
    
    # Status
    status: Mapped[str]        = mapped_column(String, default="open")  # open | closed | processing
    min_responses: Mapped[int] = mapped_column(Integer, default=5)
    target_responses: Mapped[int] = mapped_column(Integer, default=20)
    responses_count: Mapped[int]  = mapped_column(Integer, default=0)
    
    # Timestamps
    created_at: Mapped[datetime]  = mapped_column(DateTime(timezone=True), default=_now)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    responses: Mapped[list["SurveyResponse"]] = relationship(back_populates="session")


class SurveyResponse(Base):
    """
    Individual anonymous survey response.
    Collected from different organizational levels (Operativo, Táctico, Estratégico).
    """
    __tablename__ = "survey_responses"

    id: Mapped[str]             = mapped_column(UUID(as_uuid=False), primary_key=True, default=_uuid)
    session_id: Mapped[str]     = mapped_column(ForeignKey("survey_sessions.id"), nullable=False)
    
    # Respondent info (anonymous)
    respondent_hash: Mapped[str]= mapped_column(String, nullable=False)
    role: Mapped[str]           = mapped_column(String, nullable=False)  # Operativo | Táctico | Estratégico
    
    # Responses
    answers: Mapped[dict]       = mapped_column(JSONB, nullable=False)  # Likert scale answers
    open_answers: Mapped[dict | None] = mapped_column(JSONB, nullable=True)  # Open-ended answers
    completed: Mapped[bool]     = mapped_column(Boolean, default=False)
    
    # Timestamps
    submitted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)
    created_at: Mapped[datetime]   = mapped_column(DateTime(timezone=True), default=_now)

    # Relationships
    session: Mapped["SurveySession"] = relationship(back_populates="responses")


__all__ = ["SurveySession", "SurveyResponse"]
